官方文档地址：https://numpy.org/doc/  
中文网站：https://www.numpy.org.cn/

In [3]:
import numpy as np

np.__version__

'1.17.2'

#### 创建N维数组

In [5]:
# 最基本的创建N维数组的方法：np.array()
x = np.array([[2,4],[7,1]], np.int32)
x

array([[2, 4],
       [7, 1]])

In [20]:
# 创建N维数据的主要方式

# 用序列创建
x_from_arange = np.arange(20).reshape(4,5)
x_from_arange_step = np.arange(6,30,2).reshape(3,4)

# 创建 0 矩阵，1矩阵，单位矩阵 和 空矩阵
x_zeros = np.zeros((3,4))
x_ones = np.ones((2,2))
x_empty = np.empty((3,2))
x_eye = np.eye(3)

#  0 矩阵，1矩阵 和 空矩阵 可以用 _like 方法来指定形状
r = np.array([[2.3,5.1,1.2,1.9],[0,4.1,1.7,6.1],[1.0,3.9,3.2,1.1]], np.float64)
r_ones = np.ones_like(r)

In [40]:
# 其他创建N维数据的方法

# 用固定值填满
x_full = np.full((2, 3), 5)
x_full_like = np.full_like(r, 6)

# 线性空间：指定范围内等间距的数字
x_linespace = np.linspace(2, 10, 5)

# 线性空间：指定范围内以对数刻度均匀分布
x_logspace = np.logspace(2, 10, 10)

# 提取矩阵的对角线数据
m = np.array([[1,3,5],[2,4,6],[1,4,7]])
x_diag = np.diag(m)
x_diag_dim = np.diag(m,1)
x_diagflat = np.diagflat(m,1)

# 主对角线及以下均为1，其余为0的矩阵
x_tri = np.tri(5, 5, dtype=int)

# 矩阵的上三角
x_triu = np.triu(m)

# 矩阵的下三角
x_tril = np.tril(m)



array([[1, 3, 5],
       [0, 4, 6],
       [0, 0, 7]])

#### 数组索引与切片

索引是指用方括号 `[]` 来获取N维数组中的值，对于只有1个维度的数据索引方法与python中的相同，而对于更高维的数组，则需要用多维索引。

In [62]:
x_one_d_array = np.arange(0,10)
x_one_d_array[2]       # 2
x_one_d_array[-2]      # 8
x_one_d_array[3:-1]    # array([3, 4, 5, 6, 7, 8])
x_one_d_array[2:-1:2]  # array([2, 4, 6, 8])
x_one_d_array[np.array([0,-3,-6])]   # array([0, 7, 4])

array([0, 7, 4])

In [60]:
d = np.arange(16).reshape(4,4)
d[2,2]       # 10
d[2:]        # array([[ 8,  9, 10, 11],
             #       [12, 13, 14, 15]])
d[2:3]       # array([[ 8,  9, 10, 11]])
d[2:3, 1:3]  # array([[ 9, 10]])

array([[ 9, 10]])

In [66]:
# 布尔索引
d = np.arange(16).reshape(4,4)
d[d>4]

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])